services:
  - type: web
    name: ran-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://ran-8lzeudska-peteralys-projects.vercel.app 