services:
  - type: web
    name: ran-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    rootDir: .
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://ran-9s53094xu-peteralys-projects.vercel.app 